# Generated by Django 6.0.6 on 2026-06-27 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
