# Generated by Django 6.0.6 on 2026-06-27 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadreEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres_relacion', to='usuarios.estudiante')),
                ('padre', models.ForeignKey(limit_choices_to={'rol': 'padre'}, on_delete=django.db.models.deletion.CASCADE, related_name='hijos_relacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación Padre-Estudiante',
                'verbose_name_plural': 'Asignaciones Padre-Estudiante',
                'unique_together': {('padre', 'estudiante')},
            },
        ),
    ]
